#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 音频配置
#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 使用 Simplex I2S 模式（单工模式）
#define AUDIO_I2S_METHOD_SIMPLEX

// 麦克风配置 (MSM261S4030H0R)
// WS->IO13, SD->IO12, SCK->IO11
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_13
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_11
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_12

// 扬声器配置 (NS4168)
// L/RCLK->IO41, BCLK->IO40, SDATA->IO39
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_39
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_40
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_41

// 按钮配置
#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// 显示屏引脚配置 (ST7789 320x240)
#define DISPLAY_SPI_SCK_PIN  GPIO_NUM_15
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_7
#define DISPLAY_DC_PIN       GPIO_NUM_6
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_4
#define DISPLAY_RST_PIN      GPIO_NUM_5
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_16

// 显示屏驱动配置
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0

// SD卡配置 (SDSPI模式)
#define SDCARD_SDSPI_ENABLED    1
#define SDCARD_SPI_HOST         SPI3_HOST
#define SDCARD_SPI_CS           GPIO_NUM_9
#define SDCARD_SPI_MOSI         GPIO_NUM_10
#define SDCARD_SPI_MISO         GPIO_NUM_17
#define SDCARD_SPI_SCLK         GPIO_NUM_14
#define SDCARD_MOUNT_POINT      "/sdcard"

#endif // _BOARD_CONFIG_H_
